### PR TITLE
Run go mod tidy

### LINKED ISSUE #337: Automated release
https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/333 Was not automatically released.

### PR DESCRIPTION
**Pull request by mikkeloscar**
Fix master build by running `go mod tidy`.

Fix #337

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ruudk** [comment]
@mikkeloscar Can you rebase, to see if tests pass?

**Comment by mikkeloscar** [comment]
@ruudk FYI:
* I disabled Travis
* Disabled comments from coveralls
* Marked the github-actions `required`.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by ruudk** [comment]
> @ruudk FYI:
> 
> * I disabled Travis
> * Disabled comments from coveralls
> * Marked the github-actions `required`.

@mikkeloscar 🙌

**Pull request merged**
