### PR TITLE
Fix parsing of custom filters for ASG filter

### PR DESCRIPTION
**Pull request by mikkeloscar**
Fixes the filter parsing for ASG such that cluster IDs with `:` are
handled correctly.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
@jhohertz FYI

**Comment by jhohertz** [comment]
Thanks for the heads up @szuecs , tested the new version, all looks well. :+1:

**Comment by szuecs** [comment]
Thanks @jhohertz

**Pull request merged**
