### PR TITLE
Limit ingress support to only networking.k8s.io/v1

### PR DESCRIPTION
**Pull request by katyanna**
Given the deprecation of `extensions/v1beta1` and `networking.k8s.io/v1beta1`,
remove support for them.

### CODE REVIEW

**Comment by szuecs** [comment]
@katyanna please change the VERSION file to create the next minor version and explain in the readme.md section what the update to >= the new version will do.

**Comment by katyanna** [comment]
I've talked with @mikkeloscar and decided for freezing this for now so other open source users can use the older versions if they need to.

**Comment by szuecs** [comment]
Yeah true I also thought about that and you can change the default in kubernetes-on-aws which we likely already did.

**Comment by szuecs** [comment]
@katyanna I think we can now go on and drop the v1beta1 code

**Comment by katyanna** [comment]
:+1:

**Comment by katyanna** [comment]
> @katyanna please change the VERSION file to create the next minor version and explain in the readme.md section what the update to >= the new version will do.

@szuecs Is this still relevant or should we merge without changing the version?

**Comment by mikkeloscar** [comment]
> @szuecs Is this still relevant or should we merge without changing the version?

We should still change the version to indicate to users that this is no longer supported.

**Comment by katyanna** [comment]
👍

**Comment by zaklawrencea** [comment]
:+1:

**Pull request merged**
