### PR TITLE
Fix a typo in README.md

### PR DESCRIPTION
**Pull request by demonCoder95**
This fixes a small typo in the README.md file.

### CODE REVIEW

**Comment by szuecs** [comment]
Can you please do a `git amend --signoff` and force push (DCO required), thanks

**Comment by demonCoder95** [comment]
> Can you please do a `git amend --signoff` and force push (DCO required), thanks

Done!

**Comment by mikkeloscar** [comment]
👍

**Comment by szuecs** [comment]
👍

**Pull request merged**
