### PR TITLE
Added cluster ID

### LINKED ISSUE #13: Error when discovering previous ALBs
In the current implementation, the discovery of previously available ALBs in only done based on the ARN: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/worker.go#L76 
In case we have a previous existing ALB with the same ARN, this would would be discovered and attached correctly, but the target group will be empty.

### PR DESCRIPTION
**Pull request by Raffo**
Should fix #13. I will test it tomorrow and see if it covers all the cases.

### CODE REVIEW

**Comment by lmineiro** [comment]
lgtm

**Comment by Raffo** [comment]
The change works. I would address the testing in a separate PR according to what written in #3

**Comment by Raffo** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
