### PR TITLE
AwsAdapter > Enable `LogDebugWithRequestErrors` when debug mode is enabled

### PR DESCRIPTION
**Pull request by ruudk**
This makes it easier to debug issues, for example with [IMDSv2](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/309).

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@ruudk again here travis failed to update the status. could you try to retrigger the job?

**Comment by ruudk** [comment]
@mikkeloscar Is the coveralls an issue?

**Pull request merged**
