### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ruudk**
Because Travis was working so poorly I didn't notice this test was broken.

@mikkeloscar Can you please merge this when green?

### CODE REVIEW

**Comment by szuecs** [comment]
@ruudk https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/Makefile#L21 is your friend 😊

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ruudk** [comment]
@szuecs Will use that more often :) 

Can you approve so that we can merge this?

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Thanks @ruudk

**Pull request merged**
