### PR TITLE
Fix handling limit of certificates per ALB

### LINKED ISSUE #176: Cloudformation fails to apply new stacks due max certificates
Even including only 25 or less in the cloudformation stack this one fails to apply changes internally.

Once the certificate limit is reached KIAC is able to create a new one ALB stack but if the old one need to change some of their certificates it fails to update. It's common deal with this situation since every new ingress could fit their certificate in the full ALB pushing someother to the new one with spare space.

example:
Imagine a limit of 3 certs
you have one ALB with `A[a,b,c]` an a new ingress with `[d]` certificate is created in the cluster.
In the next iteration of the KIAC, detects 2 stacks and start to distribute the ingresses in this stacks with `A[d,a,b]` and `B[c]`. This leads make the upgrade of the A stack fails so I guess cloudformation is trying first to add new certs and then delete others.

In addition even having the update stack failed and rollbacked, KIAC updates ingresses statuses with the stacks. In this case statuses of `c` will point to `B` while the cert is still in `A` making a working service to fail

Also once you have the stack in `UPDATE_ROLLBACK_COMPLETE` status it is not ever touched anymore by KIAC
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/14fb0703ba0e187e7bb837bf414d36f35f3a523f/worker.go#L51-L53

This make it unusable for more than 25 certificates

### PR DESCRIPTION
**Pull request by mikkeloscar**
This fixes a couple of bugs related to exceeding the maximum number of
certificates per ALB.

It limits the max size to 24 instead of 25. This is done because we need
to duplicate the default certificate to work around a CloudFormation bug
(#162) and therefore need one extra space for this limiting the maximum
unique certificates per ALB to 24 instead of the AWS limit of 25.

It also fixes a bug in `AddIngress` which could potentially add some of
the certificates for a single ingress to a stack and the rest to
another stack resulting in an undesired state.

Thirdly it adds rollback complete states to `IsComplete()` to
automatically attempt to update stacks that are in a rollback complete
state.

Lastly it removes some of the getter methods from structs and instead
exports the fields that are needed in other packages. This was done to
make it easier to use the structs in tests and because we are not
writing Java.

Also switched from glide to dep for vendoring because I can't be dealing with glide at this point :)

Fix #176, #175, #98

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@jchanam @ese I have already tested this by creating 25+ certificates and ingresses and seen it work as expected. However, it would be great if you could also give it a go.

Test image is here:

```
registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-5
```

**Comment by ese** [comment]
Thanks @mikkeloscar for take time to look at this. I was doing some testing and results in KIAC trying to add 36 certs to the same one ALB.

checked with: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-5

Relevant log from KIAC, notice where is telling its using 36 Certs
```
2018/06/30 21:04:53 Found 40 ingress(es)
2018/06/30 21:04:53 Found 2 stack(s)
2018/06/30 21:04:54 Found 1 auto scaling group(s)
2018/06/30 21:04:54 Found 0 single instance(s)
2018/06/30 21:04:54 Found 3 EC2 instance(s)
2018/06/30 21:04:54 Have 2 model(s)
2018/06/30 21:04:54 updating "internet-facing" stack for 36 certificates / 24 ingresses
```

I am little bit lost with the way data is structured in KIAC with stacks, ingresses, certificates and other stuff. But In our testing this bug is related with the condition pointed by @jchanam here https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/175#issuecomment-399929414

Here the cloudformation template generated by KIAC took from AWS console:

```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Load Balancer for Kubernetes Ingress",
    "Parameters": {
        "LoadBalancerSchemeParameter": {
            "Type": "String",
            "Default": "internet-facing",
            "Description": "The Load Balancer scheme - 'internal' or 'internet-facing'"
        },
        "LoadBalancerSecurityGroupParameter": {
            "Type": "List\u003cAWS::EC2::SecurityGroup::Id\u003e",
            "Description": "The security group ID for the Load Balancer"
        },
        "LoadBalancerSubnetsParameter": {
            "Type": "List\u003cAWS::EC2::Subnet::Id\u003e",
            "Description": "The list of subnets IDs for the Load Balancer"
        },
        "TargetGroupHealthCheckIntervalParameter": {
            "Type": "Number",
            "Default": "10",
            "Description": "The healthcheck interval"
        },
        "TargetGroupHealthCheckPathParameter": {
            "Type": "String",
            "Default": "/kube-system/healthz",
            "Description": "The healthcheck path"
        },
        "TargetGroupHealthCheckPortParameter": {
            "Type": "Number",
            "Default": "9999",
            "Description": "The healthcheck port"
        },
        "TargetGroupTargetPortParameter": {
            "Type": "Number",
            "Default": "9999",
            "Description": "The target port"
        },
        "TargetGroupVPCIDParameter": {
            "Type": "AWS::EC2::VPC::Id",
            "Description": "The VPCID for the TargetGroup"
        }
    },
    "Resources": {
        "HTTPListener": {
            "Type": "AWS::ElasticLoadBalancingV2::Listener",
            "Properties": {
                "DefaultActions": [
                    {
                        "TargetGroupArn": {
                            "Ref": "TG"
                        },
                        "Type": "forward"
                    }
                ],
                "LoadBalancerArn": {
                    "Ref": "LB"
                },
                "Port": 80,
                "Protocol": "HTTP"
            }
        },
        "HTTPSListener": {
            "Type": "AWS::ElasticLoadBalancingV2::Listener",
            "Properties": {
                "Certificates": [
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/06454d8b-a71b-4f04-9234-fa92079896ca"
                    }
                ],
                "DefaultActions": [
                    {
                        "TargetGroupArn": {
                            "Ref": "TG"
                        },
                        "Type": "forward"
                    }
                ],
                "LoadBalancerArn": {
                    "Ref": "LB"
                },
                "Port": 443,
                "Protocol": "HTTPS"
            }
        },
        "HTTPSListenerCertificatef666bfe881b8754e2a725318a9ab9f89fbd88b3ce781582d09e35c03dae93ec8": {
            "Type": "AWS::ElasticLoadBalancingV2::ListenerCertificate",
            "Properties": {
                "Certificates": [
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/06454d8b-a71b-4f04-9234-fa92079896ca"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/065aabef-6782-4fc0-8968-34d8ee07e1ef"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/0b1140c3-81d1-4c75-a436-2bb0b8ac489a"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/0bbc91af-5be5-4898-8858-5d71c8e26f5f"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/0eccca72-e116-4b52-93d3-6fac6296bb4b"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/156fa3b5-9066-4553-8664-0f37622a2e80"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/2555c4e0-d146-47f0-ad9e-daf2fc921f21"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/2705c5d4-fd71-4719-a223-e62715c005a2"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/2bf1ed9f-7ab2-47ea-b91d-fbe4e87aa523"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/2f440756-3ffe-48d5-a069-d9ed9efd84c5"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/44e8ffc7-cd60-44ab-912a-e4930923181a"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/4a067185-bb6a-47c4-afbc-674cce0deacd"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/50bab5a9-52c8-4bae-87ac-3ee04a477433"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/55c9aedb-d648-43d6-8bfa-77917755f27f"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/6a6f40a7-638a-4265-b328-434d4b2c3801"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/73dc706c-ba7a-454e-890e-4a46ca399277"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/772783d4-bc22-430a-9471-c7a2536c2b1f"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/780b2136-09de-42f4-b40d-cadd73c3b31c"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/79910c40-df13-4565-9144-2a4ce57d3707"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/8079c4fb-41f8-4799-99d2-c1cc7b294fef"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/8765b808-8143-4c5d-ba82-f98a94b64377"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/91faa42d-ec2a-42e8-a85d-9401b5db294c"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/9e5e0863-a917-42ff-b58e-ebffb932f465"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/a206762e-9199-4e79-9d10-9b5a2d7e6d26"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/a7fa79fb-162d-4f41-bc5c-62ff11af5169"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/aebab481-a129-4f78-8d54-c6f94ee2d531"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/b493b817-4042-4157-98d5-7068df51bf03"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/c203981e-3305-4ff2-941c-3d8a67e0acbd"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/c65a7d98-0183-4b5c-84a9-b472200f1484"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/d0541f9d-6786-4953-9820-a879f6349c50"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/d1b9f40e-9b2a-480e-b6da-914515366360"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/dd70df15-7b54-43bd-a171-ff51e56d846e"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/dfd84eb6-15ff-4bb6-8849-3d4ef5ee1d03"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/e04edb53-b396-4720-be71-1e5ef30c1276"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/eb3b172d-987d-47b9-933c-ce4f6a8d6f7b"
                    },
                    {
                        "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/eed2eabb-4de9-4106-93f8-e47e1170ec7d"
                    }
                ],
                "ListenerArn": {
                    "Ref": "HTTPSListener"
                }
            }
        },
        "LB": {
            "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",
            "Properties": {
                "LoadBalancerAttributes": [
                    {
                        "Key": "idle_timeout.timeout_seconds",
                        "Value": "60"
                    }
                ],
                "Scheme": {
                    "Ref": "LoadBalancerSchemeParameter"
                },
                "SecurityGroups": {
                    "Ref": "LoadBalancerSecurityGroupParameter"
                },
                "Subnets": {
                    "Ref": "LoadBalancerSubnetsParameter"
                },
                "Tags": [
                    {
                        "Key": "StackName",
                        "Value": {
                            "Ref": "AWS::StackName"
                        }
                    }
                ]
            }
        },
        "TG": {
            "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
            "Properties": {
                "HealthCheckIntervalSeconds": {
                    "Ref": "TargetGroupHealthCheckIntervalParameter"
                },
                "HealthCheckPath": {
                    "Ref": "TargetGroupHealthCheckPathParameter"
                },
                "HealthCheckPort": {
                    "Ref": "TargetGroupHealthCheckPortParameter"
                },
                "Port": {
                    "Ref": "TargetGroupTargetPortParameter"
                },
                "Protocol": "HTTP",
                "VpcId": {
                    "Ref": "TargetGroupVPCIDParameter"
                }
            }
        }
    },
    "Outputs": {
        "LoadBalancerDNSName": {
            "Description": "DNS name for the LoadBalancer",
            "Value": {
                "Fn::GetAtt": [
                    "LB",
                    "DNSName"
                ]
            }
        },
        "TargetGroupARN": {
            "Description": "The ARN of the TargetGroup",
            "Value": {
                "Ref": "TG"
            }
        }
    }
}
```

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar from code point of view I am fine with merging. Next time it would be nicer to split into a refactor and a fix commit, sucht that it's better reviewable.
@ese can you tell us if the proposed image fixes the issue for you. I am not sure what you are trying to tell us with the CF output.

**Comment by ese** [comment]
@szuecs It doesn't fix the issue.

The CF template is what the controller is trying to apply which clearly exceeds the maximum number of certificates in an ALB (36 vs 25)

If you need help to test this with more than 25 certs I can provide help to do that.

**Comment by ese** [comment]
I tested #187 which resolve the specific problem of try to attach more than maxCertificates to one ALB.

There are other issues related with the use of more than 25 certificates but i will open new issues

**Comment by mikkeloscar** [comment]
@ese I'm on vacation this week, so will not have time to look at it until next week unfortunately. I assume your problem is because you have an existing stack with too many certificates and it doesn't recover with this version? This PR only addresses the issue of not creating a stack with more than 25 (or 24 really) certificates in the first place. Or that was the intention.

**Comment by ese** [comment]
@mikkeloscar this happens in a freshly new installation. Are you tested the behauviour with more than 25 certs?

**Comment by szuecs** [comment]
@ese freshly means, that you have no CF stacks maintained by this controller for me, is this correct?

**Comment by ese** [comment]
@szuecs Yeah. With no cloudformation stacks from the controller when deploy this version.

**Comment by szuecs** [comment]
In our dev account I tried registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-5 and it works. It creates the CF stacks, which in this case always times out. I will check, if I can fix this, but the CF stack split 27 ingress objects with 27 different certificates successfully into 2 stacks, one with 24 and the other with 3 certificates.

**Comment by szuecs** [comment]
@ese thanks for the detailed report!

**Comment by szuecs** [comment]
If I delete one ingress from a provisioned ALB I  get:

``` 
13:06:40 UTC+0200 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | kube-ingress-aws-controller-aws-170858875137-eu-central-1-kube-aws-test-1-819ffb91-46d2-452e-9613-53393b2f03fe | The  following resource(s) failed to create:  [HTTPSListenerCertificatee1bce11ca31d2b00743afcd6ebd3a32d24042a021b1c4391597ca6f59bfce0c1].
-- | -- | -- | -- | --
  | 13:06:39 UTC+0200 | CREATE_FAILED | AWS::ElasticLoadBalancingV2::ListenerCertificate | HTTPSListenerCertificatee1bce11ca31d2b00743afcd6ebd3a32d24042a021b1c4391597ca6f59bfce0c1 | The  maximum number of certificates has been reached (Service:  AmazonElasticLoadBalancingV2; Status Code: 400; Error Code:  TooManyCertificates; Request ID: 7cf18fc4-8043-11e8-b217-5ba37145ff0a)
```

**Comment by mikkeloscar** [comment]
@ese @szuecs thanks a lot for testing this so extensively!

We did not map the existing certificates on the stack to the loadBalancer state when we did the sync, this caused an unpredictable distribution of certificates between multiple stacks in each sync loop and that is why some certificates were moved between stacks and caused problems.

The bug should be fixed in the last commit, and I have tried to test this as you described and can not make it fail now, but please try it also, since you found issues which I didn't discover in the beginning :)

The latest image is:

```
registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-9
```

**Comment by mikkeloscar** [comment]
@szuecs I also split the refactoring into a separate commit so it's a bit easier to review.

**Comment by ese** [comment]
Thanks a lot @mikkeloscar. I have been testing and it seems work fine for adding certificates and I was unable to get any inconsistent state so far with last build `registry.opensource.zalan.do/teapot/kube-ingress-aws-controller-test:pr-184-9`  :smile: 
The only thing is when you delete some existing ingress in kubernetes, CF stacks updates are triggered but nothing changes in the templates so they continue having the unused certificates.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ese** [comment]
It works, thanks.

Regarding with recent release 0.7.1 it would be nice include in the release notes the change in the behaviour of `-health-check-port` and the new option `-target-port`

**Comment by mikkeloscar** [comment]
@ese Thanks, I updated the release notes.

**Pull request merged**
