### PR TITLE
Updated AWS SDK version to support native IAM

### LINKED ISSUE #269: Update the AWS SDK version to support Web Identity providers for IAM credentials
To be able to move away from kube2iam and use the new native IAM solution in EKS 1.14 the AWS SDK needs updating to at least 1.23.13

See:
* https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
* https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

### PR DESCRIPTION
**Pull request by MarcusNoble**
Fixes #269 

Update the AWS SDK version to be able to support the new IAM support in AWS EKS 1.14

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by MarcusNoble** [comment]
@hjacobs @mikkeloscar Is it possible to get this into a new release? We have some teams wanting to move off of kube2iam but can't until this is available. 😄

**Comment by szuecs** [comment]
@MarcusNoble will do, thanks for the PR

**Comment by MarcusNoble** [comment]
Awesome! Thanks for the amazingly quick response 🙂

**Comment by szuecs** [comment]
https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.8.12

**Comment by szuecs** [comment]
You were lucky, opened e-mail got yours at first :)

**Pull request merged**
