### PR TITLE
Update aws-sdk-go v1.29.34

### PR DESCRIPTION
**Pull request by ruudk**
Good to keep this up to date as they have fixed some things related to IMDSv2.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by ruudk** [comment]
Let’s merge?

**Comment by mikkeloscar** [comment]
@ruudk I think travis failed to report back after running on your fork and therefore one required check is not green so we can't merge. Any change you can re-trigger the job? https://travis-ci.org/github/zalando-incubator/kube-ingress-aws-controller/builds/668079654

**Comment by ruudk** [comment]
Travis is broken since yesterday, don't know what to do. But if you are admin you can merge it, right? Test is green.

**Pull request merged**
