### PR TITLE
fix: assume alb in case ALB feature is in use by a kubernetes resource

### PR DESCRIPTION
**Pull request by szuecs**
fix https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/428
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by mikkeloscar** [comment]
I think we also need to consider this inside the template generation logic because we do different things depending on `spec.loadbalancerType`. We have some tests for how the final cloudformation stack looks like which could be used to validate these cases.

**Comment by szuecs** [comment]
Then I think the best is to move the code to when we create spec in the adapter

**Comment by szuecs** [comment]
@mikkeloscar the problem with the CF stack generation is that they depend on

**Pull request closed without merging**
