### PR TITLE
Remove `dep` from readme

### PR DESCRIPTION
**Pull request by ruudk**
Project uses Go Modules now.

### CODE REVIEW

**Comment by szuecs** [comment]
Can you please sign-off with git amend, in repository pr like this can not be accepted because of dco 🙁

**Comment by ruudk** [comment]
What's the point of that sign off? I don't get it. It's just a text that says " Signed off " ?

**Comment by szuecs** [comment]
Compliance rules...
Thanks for doing the extra work!

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
