### PR TITLE
Use HTTP for NLB health checks

### PR DESCRIPTION
**Pull request by jonathanbeber**
When accepting HTTPS as target we made all NLBs' health check TCP. It
does not work since we set path and neither is a desired behavior,
since we want to check skipper running on these machines.

Related to https://github.com/zalando-incubator/kubernetes-on-aws/pull/4212 failures.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@jonathanbeber Thanks! Sign-off of the commit missing :)

**Comment by jonathanbeber** [comment]
argh :grimacing: thanks, just did!

**Comment by jonathanbeber** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
