### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by ruudk**
## Todo

- [ ] Coveralls, maybe do this in another PR?

### CODE REVIEW

**Comment by ruudk** [comment]
@coveralls Go away

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ruudk** [comment]
@mikkeloscar Can you also enable Github Actions? I think it's a setting. 

Should I create another PR to remove Travis? 

Right now, this thing only runs on Pull Requests. Maybe we should also trigger it on any commit to master. WDYT?

**Pull request merged**
