### PR TITLE
Drop govendor in favour of glide

### PR DESCRIPTION
**Pull request by linki**
https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/52#issuecomment-301549392

### CODE REVIEW

**Comment by Raffo** [comment]
👍

**Comment by Raffo** [comment]
Can you update the travis file accordingly? You should do `glide install --strip-vendor` in the install step.

**Comment by linki** [comment]
@Raffo done

**Comment by hjacobs** [comment]
:+1:

**Comment by Raffo** [comment]
👍

**Pull request merged**
