### PR TITLE
--debug log level options

### LINKED ISSUE #89: Enable different levels of logging
I haven't found a way to select different levels of logging

Right now the controller prints its status and information every time it polls the resources.
Would be nice to have a flag to select the desired logging level

In my case, for example, I would like to log only when the controller detects a change. Does this proposal make sense to you?

### PR DESCRIPTION
**Pull request by olevchyk**
fixes #89 
changes standard log library to logrus 
added --debug flag to increase logging level.

### CODE REVIEW

**Comment by szuecs** [comment]
Thanks!!!
Can you please change Sirupsen to lower case?

**Comment by mikkeloscar** [comment]
Also please add the library as a dependency in the Gopkg.{toml,lock} files. i.e. run: `dep ensure`.

**Comment by szuecs** [comment]
:+1:

**Comment by olevchyk** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar ready to review and merge

**Comment by mikkeloscar** [comment]
Closed in favor of #246 Thanks for the contribution @olevchyk

**Pull request closed without merging**
