### PR TITLE
Collect metrics about issued API requests

### PR DESCRIPTION
**Pull request by linki**
Just an idea how we can see how many requests to AWS and Kubernetes API we make.

Gives you something like this

```
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.5"} 66904
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.9"} 174219
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.99"} 508884
http_request_duration_microseconds_sum{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200"} 1.510416e+06
http_request_duration_microseconds_count{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200"} 14
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="200",quantile="0.5"} 481655
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="200",quantile="0.9"} 1.300036e+06
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="200",quantile="0.99"} 1.300036e+06
http_request_duration_microseconds_sum{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="200"} 1.837559e+06
http_request_duration_microseconds_count{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="200"} 3
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="301",quantile="0.5"} 1337
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="301",quantile="0.9"} 1337
http_request_duration_microseconds{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="301",quantile="0.99"} 1337
http_request_duration_microseconds_sum{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="301"} 1337
http_request_duration_microseconds_count{handler="instrumented_http",host="169.254.169.254",method="GET",path="",query="",scheme="http",status="301"} 1
http_request_duration_microseconds{handler="instrumented_http",host="acm.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.5"} 77263
http_request_duration_microseconds{handler="instrumented_http",host="acm.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.9"} 88327
http_request_duration_microseconds{handler="instrumented_http",host="acm.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.99"} 88327
http_request_duration_microseconds_sum{handler="instrumented_http",host="acm.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 350058
http_request_duration_microseconds_count{handler="instrumented_http",host="acm.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 5
http_request_duration_microseconds{handler="instrumented_http",host="autoscaling.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.5"} 63402
http_request_duration_microseconds{handler="instrumented_http",host="autoscaling.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.9"} 63402
http_request_duration_microseconds{handler="instrumented_http",host="autoscaling.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.99"} 63402
http_request_duration_microseconds_sum{handler="instrumented_http",host="autoscaling.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 63402
http_request_duration_microseconds_count{handler="instrumented_http",host="autoscaling.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 1
http_request_duration_microseconds{handler="instrumented_http",host="ec2.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.5"} 70870
http_request_duration_microseconds{handler="instrumented_http",host="ec2.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.9"} 455170
http_request_duration_microseconds{handler="instrumented_http",host="ec2.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.99"} 455170
http_request_duration_microseconds_sum{handler="instrumented_http",host="ec2.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 990311
http_request_duration_microseconds_count{handler="instrumented_http",host="ec2.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 4
http_request_duration_microseconds{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.5"} 22471
http_request_duration_microseconds{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.9"} 42610
http_request_duration_microseconds{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.99"} 130153
http_request_duration_microseconds_sum{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 1.1262961e+07
http_request_duration_microseconds_count{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 420
http_request_duration_microseconds{handler="instrumented_http",host="iam.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.5"} 114638
http_request_duration_microseconds{handler="instrumented_http",host="iam.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.9"} 388132
http_request_duration_microseconds{handler="instrumented_http",host="iam.amazonaws.com",method="POST",path="",query="",scheme="https",status="200",quantile="0.99"} 388132
http_request_duration_microseconds_sum{handler="instrumented_http",host="iam.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 732054
http_request_duration_microseconds_count{handler="instrumented_http",host="iam.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 4
```

### CODE REVIEW

**Comment by hjacobs** [comment]
Seeing the vendor code again, what about using Glide and removing the `vendor` stuff (as we do with other repos)?

**Comment by linki** [comment]
@szuecs Apart from exposing Prometheus metrics this is a single line change: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/52/commits/fe1adfd9da5c0366218f942c6986b7d13fc64bc3#diff-3f29541539ec23d8f405118c651c73c9R77

**Comment by linki** [comment]
dropping govendor https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/53

**Comment by szuecs** [comment]
@linki I don't see that you dropped the vendor folder as requested

**Comment by linki** [comment]
https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/53 hasn't been merged yet 😊  This is the former appraoch. Will rebase.

**Comment by szuecs** [comment]
:+1:

**Comment by linki** [comment]
@szuecs Updated the PR with metrics to the Kubernetes API as well. Good to go now.

One thing you already see above after a 5 minute run is

```
http_request_duration_microseconds_count{handler="instrumented_http",host="elasticloadbalancing.eu-central-1.amazonaws.com",method="POST",path="",query="",scheme="https",status="200"} 420
```

There are already 420 requests to the AWS ELB API in just 5 minutes.

**Comment by linki** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
