### PR TITLE
remove zalando.org/aws-load-balancer-ssl-cert-domain

### LINKED ISSUE #149: Removing zalando.org/aws-load-balancer-ssl-cert-domain annotation
@mikkeloscar and I agree on that the annotation `zalando.org/aws-load-balancer-ssl-cert-domain` might not be a feature anymore.
We want to ask the community if you agree or disagree and if you disagree explain why. See [this comment](https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/143#issuecomment-380913956) for why it's not needed anymore.

### PR DESCRIPTION
**Pull request by szuecs**
remove zalando.org/aws-load-balancer-ssl-cert-domain annotation

This will fix #149

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by hjacobs** [comment]
What about #170, would the annotation help in that case? (Just making sure we don't delete stuff which is still valuable)

**Comment by szuecs** [comment]
@hjacobs the name would need to be changed and reuse it to do something else is also error prone.
Additionally #170 needs to change the cf stack and we need to think about what to do in case of a changed default which does not work as we tested it.

**Pull request merged**
